version: "3.7"

services:
  postgres:
    image: bitnami/postgresql:latest
    ports:
      - "5679:5432"
    environment:
      - POSTGRES_USER=docker
      - POSTGRES_PASSWORD=docker
      - POSTGRES_DB=empybank

    volumes:
      - empybank_pg_data:/bitnami/postgresql

volumes:
  empybank_pg_data:
